### ISSUE TITLE
Laser cut material thickness

### ISSUE THREAD

**Issue by Shakunetsu** [Jrodna/OrthoCode#1]
Hi, I'm having a hard time finding how thick the laser cut pieces should be in the documentation. Can the readme be updated to include this information?

**Comment by Jrodna** [comment]
Yeah I'll add that to the readme. For your reference here the middle layers need to total at least 9mm and the base can be any thickness. The ones that were sold were either 6 and 3mm acrylic or 4.5mm acrylic.
